### PR TITLE
Minor fixes and run tests as part of github actions

### PR DESCRIPTION
**Pull request by lbscorpio**
Three minor changes and run tests in github actions.

Please help to review, thanks.

### CODE REVIEW

**Review by iamniting — CHANGES_REQUESTED** [review]
Overall changes look good to me. But we can enhance commit messages.
for example:
update go dependencies
run tests as part of github actions.

as far as I know, your code editor should sort the imports if for some reason it is not doing you should use some plugins to do that.

**Comment by lbscorpio** [comment]
@iamniting Thanks for your input, I have updated them, could you have a look when available? Thanks.

**Review by iamniting — APPROVED** [review]

**Comment by iamniting** [comment]
> @iamniting Thanks for your input, I have updated them, could you have a look when available? Thanks.

looks good to me

**Review by gongyj-ibm — APPROVED** [review]
lgtm, thanks

**Pull request merged**
