### PR TITLE
collection of updates in local

### PR DESCRIPTION
**Pull request by gyaozhou**
This is a collection of updates in local.

### CODE REVIEW

**Review by gongyj-ibm — APPROVED** [review]
lgtm, thanks a lot.

**Comment by iamniting** [comment]
@gyaozhou It is difficult for me to understand what you are trying to achieve via this PR. Can you pls update the description.

**Comment by gyaozhou** [comment]
> @gyaozhou It is difficult for me to understand what you are trying to achieve via this PR. Can you pls update the description.

We already did a lot of changes in local repository since last commit. And we will work on this repository in future.

**Comment by iamniting** [comment]
> > @gyaozhou It is difficult for me to understand what you are trying to achieve via this PR. Can you pls update the description.
> 
> We already did a lot of changes in local repository since last commit. And we will work on this repository in future.

If that's the case why don't you push all commits instead of squash them It will be easier for someone who is reviewing the changes and will give much more clarity in the commit history. It is just a suggestion and not and hard-and-fast rule.

**Comment by gyaozhou** [comment]
> > > @gyaozhou It is difficult for me to understand what you are trying to achieve via this PR. Can you pls update the description.
> > 
> > 
> > We already did a lot of changes in local repository since last commit. And we will work on this repository in future.
> 
> If that's the case why don't you push all commits instead of squash them It will be easier for someone who is reviewing the changes and will give much more clarity in the commit history. It is just a suggestion and not and hard-and-fast rule.

We use enterprise github internally, so I can't keep commit history when copy to this repo.

**Comment by jarrpa** [comment]
The way this PR is structured is not very readable and makes proper code review near impossible right now. We would really like to see the changes split up over multiple commits so that we can understand the various things being done. Without the context of *what you're trying to fix* and *why you're fixing it* we can't make meaningful judgements of whether they are implemented well or not.

If you're just using straight git against GitHub, I see no reason why you can't just directly push your entire git history. If there is some other reason, we need to be aware of what it is and see if we can work around it. Here is an example of a relatively small PR that follows the pattern we expect: https://github.com/red-hat-data-services/odf-operator/pull/5/commits

**Comment by gyaozhou** [comment]
> The way this PR is structured is not very readable and makes proper code review near impossible right now. We would really like to see the changes split up over multiple commits so that we can understand the various things being done. Without the context of _what you're trying to fix_ and _why you're fixing it_ we can't make meaningful judgements of whether they are implemented well or not.
> 
> If you're just using straight git against GitHub, I see no reason why you can't just directly push your entire git history. If there is some other reason, we need to be aware of what it is and see if we can work around it. Here is an example of a relatively small PR that follows the pattern we expect: https://github.com/red-hat-data-services/odf-operator/pull/5/commits



> The way this PR is structured is not very readable and makes proper code review near impossible right now. We would really like to see the changes split up over multiple commits so that we can understand the various things being done. Without the context of _what you're trying to fix_ and _why you're fixing it_ we can't make meaningful judgements of whether they are implemented well or not.
> 
> If you're just using straight git against GitHub, I see no reason why you can't just directly push your entire git history. If there is some other reason, we need to be aware of what it is and see if we can work around it. Here is an example of a relatively small PR that follows the pattern we expect: https://github.com/red-hat-data-services/odf-operator/pull/5/commits

I just noticed that it's feasible to push local repo to another.  Since our team work closely, and the PR opened in local is not well organised for review.  It's a lesson we need to learn. Thanks.

**Comment by iamniting** [comment]
> > The way this PR is structured is not very readable and makes proper code review near impossible right now. We would really like to see the changes split up over multiple commits so that we can understand the various things being done. Without the context of _what you're trying to fix_ and _why you're fixing it_ we can't make meaningful judgements of whether they are implemented well or not.
> > If you're just using straight git against GitHub, I see no reason why you can't just directly push your entire git history. If there is some other reason, we need to be aware of what it is and see if we can work around it. Here is an example of a relatively small PR that follows the pattern we expect: https://github.com/red-hat-data-services/odf-operator/pull/5/commits
> 
> > The way this PR is structured is not very readable and makes proper code review near impossible right now. We would really like to see the changes split up over multiple commits so that we can understand the various things being done. Without the context of _what you're trying to fix_ and _why you're fixing it_ we can't make meaningful judgements of whether they are implemented well or not.
> > If you're just using straight git against GitHub, I see no reason why you can't just directly push your entire git history. If there is some other reason, we need to be aware of what it is and see if we can work around it. Here is an example of a relatively small PR that follows the pattern we expect: https://github.com/red-hat-data-services/odf-operator/pull/5/commits
> 
> I just noticed that it's feasible to push local repo to another. Since our team work closely, and the PR opened in local is not well organised for review. It's a lesson we need to learn. Thanks.

Yes you can do push it very easily by adding a new remote to the same clone.

**Pull request merged**
